title: Humanities Without Walls Community Engaged Research Toolkit
description: Community engaged research, projects, network, resources, etc
theme: just-the-docs

color_scheme: dark

logo: "/assets/images/site_logo.png"

url: https://hwwcommunityengagedresearch.github.io

aux_links:
  Humanities Without Walls: https://www.humanitieswithoutwalls.illinois.edu/

callouts:
  new:
    title: Putting Knowledge into Practice
    color: green-000

  highlight:
    title: Resource
    color: yellow-000
    
