title: Humanities Without Walls Community Engaged Research Toolkit
description: Community engaged research, projects, network, resources
theme: just-the-docs

color_scheme: dark

logo: "/assets/images/site_logo.png"

url: https://hwwcommunityengagedresearch.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
